{
	"name": "Tasmota",
	"version": "1.1.2",
	"icon": "fab fa-battle-net",
	"category": "undefined",
	"author": "Psychokiller1888",
	"maintainers": ["maxbachmann"],
	"desc": "This skill allows you to not only connect tasmota esp devices, but listen to them",
	"aliceMinVersion": "1.0.0-a5",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de"
		],
		"online": true
	}
}
