{
	"name": "Tasmota",
	"version": "1.2.4",
	"icon": "fas fa-microchip",
	"category": "automation",
	"author": "Psychokiller1888",
	"maintainers": [
		"maxbachmann",
		"philipp2310"
	],
	"desc": "This skill allows you to not only connect tasmota esp devices, but listen to them",
	"aliceMinVersion": "1.0.0-b1",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de"
		],
		"online": true
	}
}
